### ISSUE TITLE
Regression in 1.1.2?

### ISSUE THREAD

**Issue by deeuu** [euantorano/progress.nim#7] opened 2021-02-12 11:49 UTC
Hey,

Thanks for this nice little progress bar!

Trying to install 1.1.2 on nim >= 1.2.0 but I'm getting the error
```
.nimble/pkgs/progress-1.1.2/progress.nim(81, 31) Error: in expression '0 ..len(completeBar)': identifie
r expected, but found '0'
```
Is the [`0 ..len(completeBar)`](https://github.com/euantorano/progress.nim/commit/7f6922914b5c512d9f0ed88a14f1b8cffdfff840#diff-f7f27bd0d8c0d259c52ac9bc6986846b4da536138befa08774364909aff118c3R81) slice valid?

Thanks!

**Comment by euantorano** [comment] 2021-02-12 17:19
Interesting, that does seem like a regression. It appears the problem is due to the space, having played with it on the playground. I'll create a PR and release now.

**Comment by euantorano** [comment] 2021-02-12 17:33
Should be fixed by https://github.com/euantorano/progress.nim/commit/110eac49c9247e9dc87202d6eb3cab39dd635af4 - tested locally on Windows 10 and Linux with Nim 1.4.2.

**Closed as completed by euantorano** 2021-02-12 17:33 UTC
Labels: bug
